In [19]:
import nltk
# nltk.download()


lines = [['lines is was some string of words'], ['My name is Jeff']]



def filter_nouns(data):
    
    i = 0
    nouns = None
    noun_list = []
    while i < len(data):
        lines = ''.join(data[i])
        # function to test if something is a noun
        is_noun = lambda pos: pos[:2] == 'NN'
        # do the nlp stuff
        tokenized = nltk.word_tokenize(lines)
        nouns = [word for (word, pos) in nltk.pos_tag(tokenized) if is_noun(pos)] 
        noun_list = [*noun_list, nouns]
        i += 1
        
    return noun_list
    

filter_nouns(lines)




[['lines', 'string', 'words'], ['name', 'Jeff']]

In [2]:
"""
### Problem Statement ###
Let's say you have a square matrix which consists of cosine similarities (values between 0 and 1).
This square matrix can be of any size. 
You want to get clusters which maximize the values between elemnts in the cluster.
For example, for the following matrix:
  |  A  |  B  |  C  |  D
A | 1.0 | 0.1 | 0.6 |  0.4
B | 0.1 | 1.0 | 0.1 |  0.2
C | 0.6 | 0.1 | 1.0 |  0.7
D | 0.4 | 0.2 | 0.7 |  1.0
You should get 2 clusters:
cluster #1: B
cluster #2: A, C, D
"""

import numpy as np
from sklearn.cluster import SpectralClustering
mat = np.matrix([[1.,.1,.6,.4],[.1,1.,.1,.2],[.6,.1,1.,.7],[.4,.2,.7,1.]])
SpectralClustering(2).fit_predict(mat)
# >>> array([0, 1, 0, 0], dtype=int32)

# i.e., A, C, D belong to Cluster "0"
# whereas B belongs to Cluster "1"
# The algorithm takes the top k eigenvectors of the input matrix corresponding to the largest eigenvalues, 
# then runs the k-mean algorithm on the new matrix. Here is a simple code that does this for your matrix:

from sklearn.cluster import KMeans
eigen_values, eigen_vectors = np.linalg.eigh(mat)
KMeans(n_clusters=2, init='k-means++').fit_predict(eigen_vectors[:, 2:4])
# >>> array([0, 1, 0, 0], dtype=int32)

# For the cases you want the algorithm to figure out the number of clusters by itself, 
# you can use Density Based Clustering Algorithms like DBSCAN:

from sklearn.cluster import DBSCAN
DBSCAN(min_samples=1).fit_predict(mat)
# >>> array([0, 1, 2, 2])

# Source: http://stackoverflow.com/a/30093501

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/cluster/spectral.py:462: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn("The spectral clustering API has changed. ``fit``"


array([0, 1, 2, 2])

In [26]:
# Define the documents
import numpy as np
# captions = filter_nouns(train_captions)
# print(captions)
doc_trump = "Mr. Trump became president after winning the political election. \
Though he lost the support of some republican friends, Trump is friends with President Putin"

doc_election = "President Trump says Putin had no political interference is the election outcome. \
He says it was a witchhunt by political parties. He claimed President Putin is a friend who had nothing \
to do with the election"

doc_putin = "Post elections, Vladimir Putin became President of Russia. President Putin had served as \
the Prime Minister earlier in his political career"

# documents = [doc_trump, doc_election, doc_putin]
# documents = [[doc_trump], [doc_election], [doc_putin]]
captions = [['start', 'skateboarder', 'trick', 'skateboard', 'ramp', 'end', '>'], ['start', 'person', 'air', 'skis', 'end', '>'], ['start', 'wood', 'door', 'boards', 'end', '>'], ['start', 'A', 'Do', 'Enter', 'sign', 'road', 'stadium', 'end', '>'], ['start', '>', 'Small', 'child', 'chair', 'plate', 'end', '>'], ['start', '>', 'groups', 'people', 'toilet', 'area', 'end', '>'], ['start', 'hand', 'cellphone', 'end', '>'], ['start', '>', 'People', 'computers', 'student', 'room', 'end', '>'], ['start', '>', 'birds', 'field', 'end', '>'], ['start', 'man', 'cell', 'phone', 'park', 'end', '>'], ['start', 'A', 'group', 'men', 'table', 'microphones', 'speech', 'end', '>'], ['start', 'bathroom', 'toilet', 'sprayer', 'wall', 'end', '>'], ['start', 'A', 'woman', 'bench', 'phone', 'end', '>'], ['start', 'woman', 'clock', 'purse', 'market', 'end', '>'], ['start', 'surfer', 'hand', 'signal', 'end', '>'], ['start', 'A', 'cat', 'asphalt', 'end', '>'], ['start', '>', 'carrots', 'cut', 'squash', 'carrots', 'end', '>'], ['start', '>', 'Traffic', 'lights', 'intersection', 'world', 'end', '>'], ['start', 'man', 'goatee', 'backseat', 'vehicle', 'luggage', 'end', '>'], ['start', 'A', 'street', 'sign', 'intersection', 'Beacon', 'Ave', 'Stevens', 'St.', '<', 'end', '>'], ['start', 'kid', 'skateboard', 'kid', 'end', '>'], ['start', 'A', 'apple', 'clock', 'display', 'end', '>'], ['start', 'A', 'bunch', 'color', 'watches', 'table', 'end', '>'], ['start', 'man', 'suit', 'standing', 'front', 'stove', 'end', '>'], ['start', '>', 'Pizzas', 'sauce', 'cheese', 'table', 'end', '>'], ['start', 'variety', 'vegetables', 'sticks', 'tray', 'control', 'end', '>'], ['start', 'bus', 'road', 'driver', 'end', '>'], ['start', 'A', 'pizza', 'cut', 'pieces', 'top', 'counter', 'end', '>'], ['start', 'plate', 'breakfast', 'food', 'eggs', 'toast', 'hash', 'browns', 'end', '>'], ['start', 'transit', 'bus', 'lot', 'end', '>'], ['start', 'man', 'air', 'skateboard', 'end', '>'], ['start', '>', 'ground', 'plane', 'end', '>'], ['start', 'person', 'bananas', 'back', 'end', '>'], ['start', '>', 'Three', 'zebras', 'field', 'grass', 'end', '>'], ['start', 'A', 'couple', 'pieces', 'toast', 'cup', 'syrup', 'end', '>'], ['start', '>', 'Many', 'dishes', 'people', 'end', '>'], ['start', 'herd', 'wire', 'fence', 'end', '>'], ['start', 'A', 'slice', 'pizza', 'cheese', 'crust', 'end', '>'], ['start', 'herd', 'cows', 'field', 'end', '>'], ['start', 'paper', 'plate', 'dog', 'sandwich', 'cream', 'cheese', 'end', '>'], ['start', 'baby', 'boy', 'room', 'baby', 'doll', 'end', '>'], ['start', 'man', 'woman', 'tennis', 'rackets', 'court', 'end', '>'], ['start', 'bus', 'side', 'man', 'storage', 'bus', '<', 'end', '>'], ['start', 'A', 'girl', 'man', 'tie', 'end', '>'], ['start', 'A', 'baseball', 'player', 'bat', 'game', 'end', '>'], ['start', 'man', 'ocean', 'waters', 'waves', 'end', '>'], ['start', 'A', 'couple', 'women', 'top', 'tennis', 'court', 'end', '>'], ['start', '>', 'zebra', 'end', '>'], ['start', 'clock', 'side', 'beige', 'bell', 'tower', 'end', '>'], ['start', 'bear', 'teeth', 'camera', 'end', '>'], ['start', 'A', 'remote', 'sink', 'room', 'end', '>'], ['start', 'A', 'bathroom', 'sink', 'mirror', 'toilet', 'tub', 'end', '>'], ['start', 'passenger', 'train', 'platform', 'end', '>'], ['start', 'A', 'group', 'people', 'restaurant', 'table', 'end', '>'], ['start', 'men', 'glasses', 'end', '>'], ['start', 'A', 'woman', 'slice', 'pizza', 'cheese', 'end', '>'], ['start', 'A', 'motor', 'bike', 'side', 'road', 'end', '>'], ['start', 'plate', 'foods', 'cheeses', 'end', '>'], ['start', '>', 'Donuts', 'cell', 'phone', 'table', 'end', '>'], ['start', '>', 'Six', 'plastic', 'containers', 'vegetables', 'end', '>'], ['start', 'horse', 'standing', 'front', 'portrait', 'village', 'end', '>'], ['start', 'women', 'hill', 'end', '>'], ['start', 'man', 'glasses', 'suit', 'vest', 'end', '>'], ['start', 'kitchen', 'counters', 'chrome', 'microwave', 'backsplash', 'end', '>'], ['start', 'retriever', 'dog', 'desk', 'end', '>'], ['start', 'A', 'dog', 'leash', 'reflection', 'door', 'end', '>'], ['start', 'giraffe', 'umbrella', 'end', '>'], ['start', 'skier', 'blue', 'jacket', 'goggles', 'end', '>'], ['start', 'skier', 'view', 'mountain', 'top', 'end', '>'], ['start', 'truck', 'highway', 'end', '>'], ['start', 'batter', 'plate', 'swing', 'pitch', 'end', '>'], ['start', 'train', 'towards', 'train', 'station', 'end', '>'], ['start', '>', 'People', 'baggage', 'claim', 'area', 'airport', 'end', '>'], ['start', 'bride', 'groom', 'wedding', 'cake', 'end', '>'], ['start', '>', 'Parking', 'meters', 'front', 'spaces', 'lot', 'end', '>'], ['start', 'A', 'bunch', 'road', 'signs', 'side', 'road', 'end', '>'], ['start', 'plate', 'food', 'table', 'pitchers', 'end', '>'], ['start', 'laptop', 'desk', 'coke', 'bottle', 'Apple', 'monitor', 'end', '>'], ['start', 'A', 'person', 'skis', 'lays', 'snow', 'legs', 'end', '>'], ['start', '>', 'Cars', 'street', 'traffic', 'light', 'end', '>'], ['start', '>', 'people', 'tables', 'outdoors', 'end', '>'], ['start', 'giraffe', 'boulder', 'wall', 'end', '>'], ['start', 'A', 'leather', 'chair', 'book', 'arm', 'end', '>'], ['start', 'A', 'group', 'cross', 'country', 'skiiers', 'race', 'end', '>'], ['start', 'table', 'plates', 'food', 'end', '>'], ['start', 'A', 'couple', 'animals', 'day', 'end', '>'], ['start', 'man', 'tie', 'front', 'mirror', 'end', '>'], ['start', 'cat', 'piece', 'luggage', 'end', '>'], ['start', 'elephant', 'background', 'monkey', 'sides', 'end', '>'], ['start', 'man', 'tennis', 'ball', 'end', '>'], ['start', 'A', 'bathroom', 'door', 'end', '>'], ['start', 'bar', 'blender', 'liquid', 'end', '>'], ['start', 'girafee', 'top', 'tree', 'girafee', 'end', '>'], ['start', 'A', 'clock', 'tower', 'towering', 'city', 'end', '>'], ['start', 'man', 'motor', 'cycle', 'saddle', 'bags', 'end', '>'], ['start', 'mug', 'keyboard', 'desk', 'end', '>'], ['start', 'man', 'drives', 'horse', 'carriage', 'end', '>'], ['start', '>', 'zebras', 'side', 'side', 'grass', 'end', '>'], ['start', '>', 'Inside', 'apartment', 'door', 'chairs', 'refrigerator', 'end', '>'], ['start', 'bathroom', 'beige', 'flooring', 'walls', 'end', '>']]
print(np.size(captions))

100


In [27]:
# print(captions)
# Scikit Learn
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

def construct_matrix(document):
    
    # Create the Document Term Matrix
    count_vectorizer = CountVectorizer(stop_words='english')
    count_vectorizer = CountVectorizer()
    
    i = 0
    df = None
    noun_list = []
    while i < len(document):
        j = 0
        word_list = []
        while j < len(document[i]):
            if document[i][j] == 'start':
                document[i].remove(document[i][j])
            if document[i][j] == 'end':
                document[i].remove(document[i][j])
            if document[i][j] == '>':
                document[i].remove(document[i][j])            
            j += 1
        
        noun_str = ' '.join(document[i])

        noun_list = [*noun_list, noun_str]
        i += 1

    sparse_matrix = count_vectorizer.fit_transform(noun_list)

    # OPTIONAL: Convert Sparse Matrix to Pandas Dataframe if you want to see the word frequencies.
    doc_term_matrix = sparse_matrix.todense()
    
    count = 0
    numbers = []
    while count < 100:
        count += 1
        numbers = [*numbers, "Caption {}".format(len(numbers) + 1)]
    
    df = pd.DataFrame(doc_term_matrix, 
                  columns=count_vectorizer.get_feature_names(), 
                  index=[x for x in numbers]) 

    return df

construct_matrix(captions)

air  airport  animals  apartment  apple  area  arm  asphalt  ave  \
Caption 1      0        0        0          0      0     0    0        0    0   
Caption 2      1        0        0          0      0     0    0        0    0   
Caption 3      0        0        0          0      0     0    0        0    0   
Caption 4      0        0        0          0      0     0    0        0    0   
Caption 5      0        0        0          0      0     0    0        0    0   
...          ...      ...      ...        ...    ...   ...  ...      ...  ...   
Caption 96     0        0        0          0      0     0    0        0    0   
Caption 97     0        0        0          0      0     0    0        0    0   
Caption 98     0        0        0          0      0     0    0        0    0   
Caption 99     0        0        0          1      0     0    0        0    0   
Caption 100    0        0        0          0      0     0    0        0    0   

             baby  ...  waters  waves  wedding  wire  woman  women  wood  \
Caption 1       0  ...       0      0        0     0      0      0     0   
Caption 2       0  ...       0      0        0     0      0      0     0   
Caption 3       0  ...       0      0        0     0      0      0     1   
Caption 4       0  ...       0      0        0     0      0      0     0   
Caption 5       0  ...       0      0        0     0      0      0     0   
...           ...  ...     ...    ...      ...   ...    ...    ...   ...   
Caption 96      0  ...       0      0        0     0      0      0     0   
Caption 97      0  ...       0      0        0     0      0      0     0   
Caption 98      0  ...       0      0        0     0      0      0     0   
Caption 99      0  ...       0      0        0     0      0      0     0   
Caption 100     0  ...       0      0        0     0      0      0     0   

             world  zebra  zebras  
Caption 1        0      0       0  
Caption 2        0      0       0  
Caption 3        0      0       0  
Caption 4        0      0       0  
Caption 5        0      0       0  
...            ...    ...     ...  
Caption 96       0      0       0  
Caption 97       0      0       0  
Caption 98       0      0       1  
Caption 99       0      0       0  
Caption 100      0      0       0  

[100 rows x 252 columns]

In [66]:
# sentence = ['this','is','a','sentence']
# a = ' '.join(sentence)
# print([a])


['this is a sentence']


In [109]:
documentss = [doc_trump, doc_election, doc_putin]



sparse_matrix = count_vectorizer.fit_transform(documentss)

# OPTIONAL: Convert Sparse Matrix to Pandas Dataframe if you want to see the word frequencies.
doc_term_matrix = sparse_matrix.todense()
df = pd.DataFrame(doc_term_matrix, 
              columns=count_vectorizer.get_feature_names(), 
              index=['doc_trump', 'doc_election', 'doc_putin'])

df



after  as  became  by  career  claimed  do  earlier  election  \
doc_trump         1   0       1   0       0        0   0        0         1   
doc_election      0   0       0   1       0        1   1        0         2   
doc_putin         0   1       1   0       1        0   0        1         0   

              elections  ...  the  though  to  trump  vladimir  was  who  \
doc_trump             0  ...    2       1   0      2         0    0    0   
doc_election          0  ...    2       0   1      1         0    1    1   
doc_putin             1  ...    1       0   0      0         1    0    0   

              winning  witchhunt  with  
doc_trump           1          0     1  
doc_election        0          1     1  
doc_putin           0          0     0  

[3 rows x 48 columns]

In [128]:
count = 0
numbers = []
while count < 100:
    count += 1
    numbers.append("Caption {}".format(len(numbers) + 1))

a = [x for x in numbers]
print(a)

['Caption 1', 'Caption 2', 'Caption 3', 'Caption 4', 'Caption 5', 'Caption 6', 'Caption 7', 'Caption 8', 'Caption 9', 'Caption 10', 'Caption 11', 'Caption 12', 'Caption 13', 'Caption 14', 'Caption 15', 'Caption 16', 'Caption 17', 'Caption 18', 'Caption 19', 'Caption 20', 'Caption 21', 'Caption 22', 'Caption 23', 'Caption 24', 'Caption 25', 'Caption 26', 'Caption 27', 'Caption 28', 'Caption 29', 'Caption 30', 'Caption 31', 'Caption 32', 'Caption 33', 'Caption 34', 'Caption 35', 'Caption 36', 'Caption 37', 'Caption 38', 'Caption 39', 'Caption 40', 'Caption 41', 'Caption 42', 'Caption 43', 'Caption 44', 'Caption 45', 'Caption 46', 'Caption 47', 'Caption 48', 'Caption 49', 'Caption 50', 'Caption 51', 'Caption 52', 'Caption 53', 'Caption 54', 'Caption 55', 'Caption 56', 'Caption 57', 'Caption 58', 'Caption 59', 'Caption 60', 'Caption 61', 'Caption 62', 'Caption 63', 'Caption 64', 'Caption 65', 'Caption 66', 'Caption 67', 'Caption 68', 'Caption 69', 'Caption 70', 'Caption 71', 'Caption 72', 